# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "http://vivekbhanot.com"
baseurl: ""

# Brief name and description of the site
title: Vivek Bhanot
description: "Data Governance, Data Management, BI & Analytics Professional"

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/vivek-bhanot.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Gallery: ""
  Contact: "contact"
nav-search: "search"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Vivek Bhanot
  email: "vivek.vb239@gmail.com"
  linkedin: "in/vibhanot"
  
# Select which links to show in the footer  
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  github: false
  linkedin: true
  stackoverflow: false
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "vivekbhanot.com" 

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-59820529-1"  # Your Google Analytics ID

fb_app_id: "536330676521989"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
      comments: false  # add comments to all blog posts 		
      show-share: false # add sharing buttons to all blog posts		
      show-subscribe: false # add subscribe email to all blog posts
      addthis-plugin: false
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# 2fc73a3a967e97599c9763d05e564189
